import mongoose from "mongoose";

const jobSchema=new mongoose.Schema({
    title:{
        type:String,
        required:true,
    },
    description:{
        type:String,
        required:true,
    },
    experienceLevel:{
        type:String,
        required:true,
    },
    employmentType:{
        type:String,
        required:true,
    },
    jobType:{
        type:String,
        required:true,
    },
    location:{
        type:String,
        required:true,
    },
    positions:{
        type:Number,
        required:true,
    },
    salary:{
        type:Number,
        required:true,
    },
    company:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Company',
        required:true,
    },
    applications:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Application',
    }],
    deadline:{
        type:Date,
        required:true,
    },
    filled:{
        type:Boolean,
        default:false,
    },
    requirements:[{
        type:String,
    }],
    createdby:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true,
    },
},{timestamps:true});

export default mongoose.model('Job',jobSchema);