import mongoose from 'mongoose'

const userSchema = new mongoose.Schema({
    name:{
        type:String,
        required:true,
        trim:true,
        min:3,
        max:20,
    },
    email:{
        type:String,
        required:true,
        trim:true,
        unique:true,
    },
    password:{
        type:String,
        required:true,
    },
    mobileNumber:{
        type:String,
        required:true,
        trim:true,
        max:10,
    },
    role:{
        type:String,
        enum:['candidate','recruiter'],
        required:true,
    },
    profile:{
        bio:{
            type:String,
        },
        skills:[{type:String}],
        resume:{
            type:String,
        },
        company:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Company',
        },
        education:[{
            degree:{
                type:String,
            },
            institution:{
                type:String,
            },
            passingYear:{
                type:String,
            },
        }],
        experience:[{
            title:{
                type:String,
            },
            company:{
                type:String,
            },
            location:{
                type:String,
            },
            from:{
                type:Date,
            },
            to:{
                type:Date,
            },
            current:{
                type:Boolean,
                default:false,
            },
            description:{
                type:String,
            },
        }],
        social:{
            github:{
                type:String,
            },
            linkedin:{
                type:String,
            },
        },
        profilePicture:{
            type:String,
        },
        }
},{timestamps:true});

export default mongoose.model('User',userSchema);